---
apiVersion: v1
kind: Service
metadata:
  name: cs-service
  labels:
    name: cs-service
    app: phoenix-app
spec:
  ports:
  - port: 
    targetPort: 
  selector:
    name: cs-app-pod
    app: cs-app