---
apiVersion: v1
kind: Service
metadata:
  name: js-service
  labels:
    name: js-service
    app: phoenix-app
spec:
  ports:
  - port: 
    targetPort: 
  selector:
    name: js-app-pod
    app: js-app