---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-deploy
  labels:
    name: postgres-deploy
    app: phoenix-app
spec:
  replicas: 1
  selector:     # selector labels should match with template > metadata > labels
    matchLabels:
      name: postgres-pod
      app: phoenix-app
  template:
    metadata:
      name: postgres-pod
      labels:
        name: postgres-pod
        app: phoenix-app
    spec:
      containers:
      - name: postgres
        image: postgres:16.0-bookworm
        ports:
        - containerPort: 5432
        env:
          - name: POSTGRES_USER
            value: "hello"
          - name: POSTGRES_PASSWORD
            value: "password"
          - name: POSTGRES_HOST_AUTH_METHOD
            value: trust

