---
apiVersion: v1
kind: Service
metadata:
  name: web-service
  labels:
    name: web-service
    app: phoenix-app
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 8000
    nodePort: 8000
  selector:
    name: web-app-pod
    app: web-app